import type { Child, VaccinationRecord, Reminder, Clinic } from "./types"

export const mockChildren: Child[] = [
  {
    id: "child-1",
    name: "Emma Johnson",
    dateOfBirth: "2023-06-15",
    gender: "female",
    avatarColor: "bg-pink-100 text-pink-600",
  },
  {
    id: "child-2",
    name: "Liam Johnson",
    dateOfBirth: "2021-03-22",
    gender: "male",
    avatarColor: "bg-blue-100 text-blue-600",
  },
]

export const mockVaccinationRecords: VaccinationRecord[] = [
  // Emma's records
  {
    id: "vr-1",
    childId: "child-1",
    vaccineId: "hepb-1",
    scheduledDate: "2023-06-15",
    administeredDate: "2023-06-15",
    status: "completed",
    administeredBy: "Dr. Sarah Chen",
    location: "City Hospital",
  },
  {
    id: "vr-2",
    childId: "child-1",
    vaccineId: "dtap-1",
    scheduledDate: "2023-08-15",
    administeredDate: "2023-08-17",
    status: "completed",
    administeredBy: "Dr. Sarah Chen",
    location: "City Hospital",
  },
  {
    id: "vr-3",
    childId: "child-1",
    vaccineId: "ipv-1",
    scheduledDate: "2023-08-15",
    administeredDate: "2023-08-17",
    status: "completed",
    administeredBy: "Dr. Sarah Chen",
    location: "City Hospital",
  },
  {
    id: "vr-4",
    childId: "child-1",
    vaccineId: "hib-1",
    scheduledDate: "2023-08-15",
    administeredDate: "2023-08-17",
    status: "completed",
    administeredBy: "Dr. Sarah Chen",
    location: "City Hospital",
  },
  {
    id: "vr-5",
    childId: "child-1",
    vaccineId: "pcv-1",
    scheduledDate: "2023-08-15",
    administeredDate: "2023-08-17",
    status: "completed",
    administeredBy: "Dr. Sarah Chen",
    location: "City Hospital",
  },
  {
    id: "vr-6",
    childId: "child-1",
    vaccineId: "rv-1",
    scheduledDate: "2023-08-15",
    administeredDate: "2023-08-17",
    status: "completed",
    administeredBy: "Dr. Sarah Chen",
    location: "City Hospital",
  },
  {
    id: "vr-7",
    childId: "child-1",
    vaccineId: "dtap-2",
    scheduledDate: "2023-10-15",
    administeredDate: "2023-10-18",
    status: "completed",
    administeredBy: "Dr. Sarah Chen",
    location: "City Hospital",
  },
  {
    id: "vr-8",
    childId: "child-1",
    vaccineId: "ipv-2",
    scheduledDate: "2023-10-15",
    administeredDate: "2023-10-18",
    status: "completed",
    administeredBy: "Dr. Sarah Chen",
    location: "City Hospital",
  },
  {
    id: "vr-9",
    childId: "child-1",
    vaccineId: "mmr-1",
    scheduledDate: "2024-06-15",
    status: "upcoming",
  },
  {
    id: "vr-10",
    childId: "child-1",
    vaccineId: "var-1",
    scheduledDate: "2024-06-15",
    status: "upcoming",
  },
  // Liam's records
  {
    id: "vr-20",
    childId: "child-2",
    vaccineId: "hepb-1",
    scheduledDate: "2021-03-22",
    administeredDate: "2021-03-22",
    status: "completed",
    administeredBy: "Dr. Michael Park",
    location: "Children's Medical Center",
  },
  {
    id: "vr-21",
    childId: "child-2",
    vaccineId: "dtap-1",
    scheduledDate: "2021-05-22",
    administeredDate: "2021-05-24",
    status: "completed",
    administeredBy: "Dr. Michael Park",
    location: "Children's Medical Center",
  },
  {
    id: "vr-22",
    childId: "child-2",
    vaccineId: "mmr-1",
    scheduledDate: "2022-03-22",
    administeredDate: "2022-03-25",
    status: "completed",
    administeredBy: "Dr. Michael Park",
    location: "Children's Medical Center",
  },
  {
    id: "vr-23",
    childId: "child-2",
    vaccineId: "var-1",
    scheduledDate: "2022-03-22",
    administeredDate: "2022-03-25",
    status: "completed",
    administeredBy: "Dr. Michael Park",
    location: "Children's Medical Center",
  },
  {
    id: "vr-24",
    childId: "child-2",
    vaccineId: "dtap-5",
    scheduledDate: "2025-03-22",
    status: "upcoming",
  },
  {
    id: "vr-25",
    childId: "child-2",
    vaccineId: "ipv-4",
    scheduledDate: "2025-03-22",
    status: "upcoming",
  },
  {
    id: "vr-26",
    childId: "child-2",
    vaccineId: "mmr-2",
    scheduledDate: "2025-03-22",
    status: "upcoming",
  },
  {
    id: "vr-27",
    childId: "child-2",
    vaccineId: "flu-1",
    scheduledDate: "2026-01-20",
    status: "overdue",
  },
]

export const mockReminders: Reminder[] = [
  {
    id: "rem-1",
    childId: "child-1",
    vaccinationRecordId: "vr-9",
    reminderDate: "2024-06-10",
    type: "email",
    status: "pending",
  },
  {
    id: "rem-2",
    childId: "child-2",
    vaccinationRecordId: "vr-24",
    reminderDate: "2025-03-15",
    type: "push",
    status: "pending",
  },
]

export const mockClinics: Clinic[] = [
  {
    id: "clinic-1",
    name: "City Children's Hospital",
    address: "123 Healthcare Blvd",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    phone: "(415) 555-0101",
    website: "https://citychildrens.example.com",
    email: "contact@citychildrens.example.com",
    type: "hospital",
    services: ["Pediatric Vaccinations", "Well-child visits", "Emergency Care", "Specialist Referrals"],
    acceptsInsurance: true,
    insuranceAccepted: ["Blue Cross", "Aetna", "United Healthcare", "Cigna", "Medicare"],
    hours: [
      { day: "Monday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Tuesday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Wednesday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Thursday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Friday", open: "8:00 AM", close: "5:00 PM" },
      { day: "Saturday", open: "9:00 AM", close: "2:00 PM" },
      { day: "Sunday", open: "Closed", close: "Closed" },
    ],
    rating: 4.8,
    reviewCount: 342,
    distance: 1.2,
    coordinates: { lat: 37.7749, lng: -122.4194 },
  },
  {
    id: "clinic-2",
    name: "Sunshine Pediatrics",
    address: "456 Kids Way",
    city: "San Francisco",
    state: "CA",
    zipCode: "94110",
    phone: "(415) 555-0202",
    website: "https://sunshinepeds.example.com",
    type: "pediatric",
    services: ["Pediatric Vaccinations", "Well-child visits", "Developmental Screenings", "Sick visits"],
    acceptsInsurance: true,
    insuranceAccepted: ["Blue Cross", "Kaiser", "United Healthcare"],
    hours: [
      { day: "Monday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Tuesday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Wednesday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Thursday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Friday", open: "9:00 AM", close: "4:00 PM" },
      { day: "Saturday", open: "Closed", close: "Closed" },
      { day: "Sunday", open: "Closed", close: "Closed" },
    ],
    rating: 4.9,
    reviewCount: 218,
    distance: 2.5,
    coordinates: { lat: 37.7599, lng: -122.4148 },
  },
  {
    id: "clinic-3",
    name: "CVS Pharmacy - Market St",
    address: "789 Market Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    phone: "(415) 555-0303",
    website: "https://cvs.example.com",
    type: "pharmacy",
    services: ["Flu Shots", "COVID-19 Vaccines", "Travel Vaccinations", "Immunization Records"],
    acceptsInsurance: true,
    insuranceAccepted: ["Most major insurance plans"],
    hours: [
      { day: "Monday", open: "8:00 AM", close: "9:00 PM" },
      { day: "Tuesday", open: "8:00 AM", close: "9:00 PM" },
      { day: "Wednesday", open: "8:00 AM", close: "9:00 PM" },
      { day: "Thursday", open: "8:00 AM", close: "9:00 PM" },
      { day: "Friday", open: "8:00 AM", close: "9:00 PM" },
      { day: "Saturday", open: "9:00 AM", close: "6:00 PM" },
      { day: "Sunday", open: "10:00 AM", close: "5:00 PM" },
    ],
    rating: 4.2,
    reviewCount: 89,
    distance: 0.8,
    coordinates: { lat: 37.7847, lng: -122.4089 },
  },
  {
    id: "clinic-4",
    name: "SF Department of Public Health",
    address: "101 Grove Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    phone: "(415) 555-0404",
    website: "https://sfdph.example.gov",
    email: "vaccines@sfdph.example.gov",
    type: "health_department",
    services: ["Free Childhood Vaccinations", "Immunization Records", "Travel Health", "Health Education"],
    acceptsInsurance: true,
    insuranceAccepted: ["All insurance accepted", "Uninsured welcome"],
    hours: [
      { day: "Monday", open: "8:30 AM", close: "5:00 PM" },
      { day: "Tuesday", open: "8:30 AM", close: "5:00 PM" },
      { day: "Wednesday", open: "8:30 AM", close: "5:00 PM" },
      { day: "Thursday", open: "8:30 AM", close: "5:00 PM" },
      { day: "Friday", open: "8:30 AM", close: "4:00 PM" },
      { day: "Saturday", open: "Closed", close: "Closed" },
      { day: "Sunday", open: "Closed", close: "Closed" },
    ],
    rating: 4.5,
    reviewCount: 156,
    distance: 1.5,
    coordinates: { lat: 37.7785, lng: -122.4156 },
  },
  {
    id: "clinic-5",
    name: "Bay Area Urgent Care",
    address: "555 Castro Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94114",
    phone: "(415) 555-0505",
    website: "https://bayareauc.example.com",
    type: "urgent_care",
    services: ["Walk-in Vaccinations", "Urgent Care", "Minor Injuries", "Illness Treatment"],
    acceptsInsurance: true,
    insuranceAccepted: ["Blue Cross", "Aetna", "United Healthcare", "Cigna"],
    hours: [
      { day: "Monday", open: "7:00 AM", close: "10:00 PM" },
      { day: "Tuesday", open: "7:00 AM", close: "10:00 PM" },
      { day: "Wednesday", open: "7:00 AM", close: "10:00 PM" },
      { day: "Thursday", open: "7:00 AM", close: "10:00 PM" },
      { day: "Friday", open: "7:00 AM", close: "10:00 PM" },
      { day: "Saturday", open: "8:00 AM", close: "8:00 PM" },
      { day: "Sunday", open: "8:00 AM", close: "8:00 PM" },
    ],
    rating: 4.3,
    reviewCount: 203,
    distance: 3.1,
    coordinates: { lat: 37.7614, lng: -122.4350 },
  },
  {
    id: "clinic-6",
    name: "Golden Gate Pediatric Associates",
    address: "200 California Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94111",
    phone: "(415) 555-0606",
    email: "appointments@ggpeds.example.com",
    type: "pediatric",
    services: ["Pediatric Vaccinations", "Newborn Care", "Adolescent Medicine", "ADHD Evaluations"],
    acceptsInsurance: true,
    insuranceAccepted: ["Blue Cross", "Aetna", "Kaiser", "United Healthcare"],
    hours: [
      { day: "Monday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Tuesday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Wednesday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Thursday", open: "8:00 AM", close: "6:00 PM" },
      { day: "Friday", open: "8:00 AM", close: "5:00 PM" },
      { day: "Saturday", open: "9:00 AM", close: "1:00 PM" },
      { day: "Sunday", open: "Closed", close: "Closed" },
    ],
    rating: 4.7,
    reviewCount: 178,
    distance: 2.8,
    coordinates: { lat: 37.7932, lng: -122.3990 },
  },
]
